### ISSUE TITLE
CUDA out of Memory Error

### ISSUE THREAD

**Issue by coolsaint** [nateraw/lightning-pretrain-hf#1]
I have tried to run it in several different setup but unfortunately got stuck with CUDA out of Memory error.

RuntimeError: CUDA out of memory. Tried to allocate 384.00 MiB (GPU 0; 15.75 GiB total capacity; 14.00 GiB already allocated; 316.81 MiB free; 14.17 GiB reserved in total by PyTorch)

**Comment by nateraw** [comment]
I'm not 100% sure what this issue is, but I was seeing it too. didn't get the chance to debug yet. When was this error being thrown for you?  If I remember correctly, I was seeing it `on_validation_epoch_end`, which leads me to believe its some aggregation issue.

If you have a full stack trace you can copy paste here before I get to it, that would be awesome! 😄 

---

As sanity check, you can limit the dataset a bit like I did in previous commit...

https://github.com/nateraw/lightning-pretrain-hf/blob/4e092deb56b4c43566316afe765e1385dd1a8f7c/data.py#L50-L57

**Comment by coolsaint** [comment]
This is the error I am getting now 

> Traceback (most recent call last):
>   File "train.py", line 50, in <module>
>     trainer.fit(model, dm)
>   File "/home/coolsaint/miniconda3/envs/pylight/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 439, in fit
>     results = self.accelerator_backend.train()
>   File "/home/coolsaint/miniconda3/envs/pylight/lib/python3.7/site-packages/pytorch_lightning/accelerators/gpu_accelerator.py", line 54, in train
>     results = self.train_or_test()
>   File "/home/coolsaint/miniconda3/envs/pylight/lib/python3.7/site-packages/pytorch_lightning/accelerators/accelerator.py", line 66, in train_or_test
>     results = self.trainer.train()
>   File "/home/coolsaint/miniconda3/envs/pylight/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 461, in train
>     self.run_sanity_check(self.get_model())
>   File "/home/coolsaint/miniconda3/envs/pylight/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 637, in run_sanity_check
>     self.reset_val_dataloader(ref_model)
>   File "/home/coolsaint/miniconda3/envs/pylight/lib/python3.7/site-packages/pytorch_lightning/trainer/data_loading.py", line 316, in reset_val_dataloader
>     self.num_val_batches, self.val_dataloaders = self._reset_eval_dataloader(model, 'val')
>   File "/home/coolsaint/miniconda3/envs/pylight/lib/python3.7/site-packages/pytorch_lightning/trainer/data_loading.py", line 236, in _reset_eval_dataloader
>     dataloaders = self.request_dataloader(getattr(model, loader_name))
>   File "/home/coolsaint/miniconda3/envs/pylight/lib/python3.7/site-packages/pytorch_lightning/trainer/data_loading.py", line 339, in request_dataloader
>     dataloader = dataloader_fx()
>   File "/home/coolsaint/pylight/data.py", line 66, in val_dataloader
>     return DataLoader(self.ds['validation'], batch_size=self.batch_size, num_workers=self.num_workers, collate_fn=self.collate_fn)
> KeyError: 'validation'

**Comment by nateraw** [comment]
Ah yea in this case just replace 'validation' with 'test'. If you init the dm and then call setup, you should be able to call dm.ds.keys() to see what splits are available
